name: Capability Architecture CI - DISABLED

on:
  # Disabled during production deployment phase
  # push:
  #   branches: [ main, develop ]
  #   paths:
  #     - 'packages/**'
  #     - 'pnpm-workspace.yaml'
  #     - 'turbo.json'
  #     - '.github/workflows/capability-ci.yml'
  # pull_request:
  #   branches: [ main, develop ]
  #   paths:
  #     - 'packages/**'
  #     - 'pnpm-workspace.yaml'
  #     - 'turbo.json'
  workflow_dispatch:

jobs:
  capability-validation:
    runs-on: ubuntu-latest
    if: false  # Disabled
    
    strategy:
      matrix:
        node-version: [22]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Validate OpenAPI contracts
      run: pnpm turbo run validate-contracts
      continue-on-error: true  # Phase 0: contracts don't exist yet
    
    - name: Generate client SDKs
      run: pnpm turbo run generate-clients
      continue-on-error: true  # Phase 0: no contracts to generate from yet
    
    - name: Type check all packages
      run: pnpm turbo run type-check
      continue-on-error: true  # Phase 0: packages don't have TypeScript yet
    
    - name: Run unit tests
      run: pnpm turbo run test
      continue-on-error: true  # Phase 0: no tests yet
    
    - name: Smoke test - Health endpoint
      run: |
        # This will be enabled in Phase 1+
        echo "Smoke tests not yet implemented (Phase 0)"
      continue-on-error: true
    
    - name: Build packages
      run: pnpm turbo run build
      continue-on-error: true  # Phase 0: no build scripts yet

  cost-validation:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    
    - name: Run cost sanity check
      run: |
        if [ -f "scripts/cost-sanity-check.js" ]; then
          node scripts/cost-sanity-check.js
        else
          echo "Cost check script not found, skipping"
        fi
      continue-on-error: true
    
    - name: Comment cost status
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🏦 **Cost Check**: Phase 0 scaffolding only - no AWS resources created. Expected cost: $0.00'
          })
